export const ERROR = 'ERROR';
export const FETCH_VIDEO_TRANSCRIPT = 'FETCH_VIDEO_TRANSCRIPT';
export const SET_VIDEOS_RESULTS = 'SET_VIDEOS_RESULTS';
export const SET_CURRENT_SESSION = 'SET_CURRENT_SESSION';
export const SET_SELECTED_VIDEOS = 'SET_SELECTED_VIDEOS';
export const UPDATE_VIDEO_CONTENT = 'UPDATE_VIDEO_CONTENT';
export const SET_CURRENT_VIDEO = 'SET_CURRENT_VIDEO';
